apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-registration-gcp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG/multicloud-student-registration.git
    targetRevision: main
    path: helm/student-registration
    helm:
      valueFiles:
        - ../../deploy/values/gcp.yaml
  destination:
    name: gcp-gke
    namespace: student-registration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
