apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {app: student-registration-frontend}
  template:
    metadata:
      labels: {app: student-registration-frontend}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports: [{containerPort: 80}]
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: student-registration-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector: {app: student-registration-frontend}
  ports:
    - port: 80
      targetPort: 80
