apiVersion: v1
kind: Secret
metadata:
  name: student-registration-db-secret
  namespace: student-registration
type: Opaque
stringData:
  DB_URL: "jdbc:mariadb://<MARIADB_SERVICE>:3306/student_registration"
  DB_USER: "<DB_USER>"
  DB_PASSWORD: "<DB_PASSWORD>"
