apiVersion: v1
kind: Secret
metadata:
  name: student-registration-db-secret
  namespace: student-registration
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://<CLOUD_SQL_PRIVATE_IP>:3306/student_registration?allowPublicKeyRetrieval=true"
  DB_USER: "<DB_USER>"
  DB_PASSWORD: "<DB_PASSWORD>"
